#### Automatically build and upload releases to GitHub ####

on:
  workflow_dispatch:
  push:
    tags:
      - "r*"
    branches: 
      - master
  pull_request: # The branches below must be a subset of the branches in "push"
    branches: 
      - master
  schedule:
    - cron: '23 11 * * 6'
name:                               Auto-Build
jobs:
  create_release:
     name:                          Create release
     runs-on:                       ubuntu-latest
     outputs:
      publish_to_release:           ${{ steps.jamulus-build-vars.outputs.PUBLISH_TO_RELEASE }}
      upload_url:                   ${{ steps.create_release_step.outputs.upload_url }}
      version:                      ${{ steps.jamulus-build-vars.outputs.JAMULUS_VERSION }}
      version_name:                 ${{ steps.jamulus-build-vars.outputs.RELEASE_VERSION_NAME }}

     steps:
         # Checkout code
         - name:                    Checkout code
           uses:                    actions/checkout@v2

         # Set variables
         # Determine release / pre-release
         - name:                    Get Jamulus build info, determine actions & variables
           run:                     python3 ${{ github.workspace }}/.github/actions_scripts/analyse_git_reference.py
           id:                      jamulus-build-vars

         # remove release, if it exists (with this releasetag)
         - name:                    Remove release, if existing (for latest and branches)
           if:                      ${{ contains(steps.jamulus-build-vars.outputs.PUBLISH_TO_RELEASE, 'true') }}
           continue-on-error:       true
           uses:                    dev-drprasad/delete-tag-and-release@v0.1.2
           with:
             delete_release:        false
             tag_name:              ${{ steps.jamulus-build-vars.outputs.RELEASE_TAG }}
           env:
             GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
         # create release (empty, filled by next jobs)
         - name:                    'Create Release ${{steps.jamulus-build-vars.outputs.RELEASE_TAG}}  {{steps.jamulus-build-vars.outputs.RELEASE_TITLE}}'
           if:                      ${{ contains(steps.jamulus-build-vars.outputs.PUBLISH_TO_RELEASE, 'true') }}
           id:                      create_release_step
           uses:                    actions/create-release@v1
           env:
             GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
           with:
             tag_name:              ${{ steps.jamulus-build-vars.outputs.RELEASE_TAG }}
             release_name:          ${{ steps.jamulus-build-vars.outputs.RELEASE_TITLE }}
             body_path:             ${{ github.workspace }}/autoLatestChangelog.md
             prerelease:            ${{ steps.jamulus-build-vars.outputs.IS_PRERELEASE }}
             draft:                 false


         ### CANCEL ### can be used for development concerning release-creation
         #- name:                    Cancelthrougherroe
         #  run:                     myundefinedfunction


  release_assets:
    name:                           Build assets for ${{ matrix.config.config_name }}
    needs:                          create_release
    runs-on:                        ${{ matrix.config.building_on_os }}
    strategy:
      fail-fast:                    false
      matrix: # Think of this like a foreach loop. Basically runs the steps with every combination of the contents of this. More info: https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
        config:
           - config_name:           Linux2 (normal)
             target_os:             linux2
             building_on_os:        ubuntu-18.04
             asset_path:            deploy/Jamulus_amd64.deb
             asset_name:            jamulus_${{ needs.create_release.outputs.version_name }}_ubuntu_amd64.deb
           - config_name:           Linux (normal)
             target_os:             linux
             building_on_os:        ubuntu-18.04
             asset_path:            deploy/Jamulus_amd64.deb
             asset_name:            jamulus_${{ needs.create_release.outputs.version_name }}_ubuntu_amd64.deb
           - config_name:           Linux (headless)
             target_os:             linux
             building_on_os:        ubuntu-18.04
             asset_path:            deploy/Jamulus_headless_amd64.deb
             asset_name:            jamulus_headless_${{ needs.create_release.outputs.version_name }}_ubuntu_amd64.deb
           - config_name:           MacOS
             target_os:             macos
             building_on_os:        macos-10.15
             asset_path:            deploy/Jamulus-installer-mac.dmg
             asset_name:            jamulus_${{ needs.create_release.outputs.version_name }}_mac.dmg
           - config_name:           Windows
             target_os:             windows
             building_on_os:        windows-latest
             asset_path:            deploy\Jamulus-installer-win.exe
             asset_name:            jamulus_${{ needs.create_release.outputs.version_name }}_win.exe
           - config_name:           AndroidAPK
             target_os:             android
             building_on_os:        ubuntu-18.04
             asset_path:            android-build/build/outputs/apk/debug/android-build-debug.apk
             asset_name:            jamulus_${{ needs.create_release.outputs.version_name }}_android.apk
    steps:

      # Checkout code
      - name:                       Checkout code
        uses:                       actions/checkout@v2
        with:
          submodules:               true
          
      # Initialize CodeQL tools for code-scanning for security
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'cpp' 
          # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
          # Learn more:
          # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

      # Build
      - name:                       "Build deb (Linux)"
        if:                         matrix.config.target_os == 'linux'
        run:                        sh linux/autorelease_linux.sh ${{ github.workspace }}
      - name:                       "Build deb (Linux)"
        if:                         matrix.config.target_os == 'linux2'
        run:                        sh ./autobuild/linux/code_ql/autorelease_linux_codeql.sh ${{ github.workspace }}
        
      - name:                       "Build (Windows)"
        if:                         matrix.config.target_os == 'windows'
        run:                        powershell .\windows\autorelease_windows.ps1 -sourcepath "${{ github.workspace }}"
      - name:                       "Build (macOS)"
        if:                         matrix.config.target_os == 'macos'
        run:                        sh mac/autorelease_mac.sh ${{ github.workspace }}
      - name:                       "Build (Android)"
        if:                         matrix.config.target_os == 'android'   
        uses:                       ./autobuild/android/ # Uses an action in the directory

      # Upload Artifact to Job
      - name:                       Upload Artifact to Job
        uses:                       actions/upload-artifact@v2
        with:
          name:                     ${{ matrix.config.asset_name }}
          path:                     ${{ matrix.config.asset_path }}
          retention-days:           14
          
      # Run CodeQL tools for code-scanning for security
      - name: Perform CodeQL Analysis
        if:                         matrix.config.target_os != 'android'   
        uses: github/codeql-action/analyze@v1
        
      # Upload Artifact to Release
      - name:                       Upload Artifact to Release
        if:                         ${{ contains(needs.create_release.outputs.publish_to_release, 'true') }}
        id:                         upload-release-asset
        uses:                       actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:               ${{ needs.create_release.outputs.upload_url }} # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path:               ${{ matrix.config.asset_path }}
          asset_name:               ${{ matrix.config.asset_name }}
          asset_content_type:       application/octet-stream
          
  ## Builds a Linux flatpack ##
  flatpak-builder:
    name: "Flatpak Builder"
    if:                         ${{ contains(needs.create_release.outputs.publish_to_release, 'true') }}
    runs-on: ubuntu-latest
    needs: [create_release]
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name:                       Change branch name in manifest
      run:                        python3 io.jamulus.Jamulus.prepare.py $GITHUB_SHA
      working-directory:          ./distributions/
    - uses:                       bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle:                   "io.jamulus.Jamulus.flatpak"
        manifest-path:            "distributions/io.jamulus.Jamulus.json"
        
    # download artifact
    - uses:                       actions/download-artifact@v2
      with:
        name:                     io.jamulus.Jamulus
        path:                     ~/io.jamulus.Jamulus
        retention-days:           14
        
    # Upload Artifact to Release
    - name:                       Upload Flatpack
      if:                         ${{ contains(needs.create_release.outputs.publish_to_release, 'true') }}
      id:                         upload-release-asset
      uses:                       actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url:               ${{ needs.create_release.outputs.upload_url }} # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path:               /github/home/io.jamulus.Jamulus/io.jamulus.Jamulus.flatpak
        asset_name:               io.jamulus.Jamulus.flatpak
        asset_content_type:       application/octet-stream