#### Automatically build and upload releases to GitHub ####

on:
  [workflow_dispatch, push]
name:                               MyTests
jobs:        
  release_win:
    name:                           Bsdyyyyyyyys
    steps:
      - name:                       AutobuildAutobuild
        uses:                       ./windows/autobuild
        
  release_apk:
    name:                           Bsdaaaaaa
    steps:
      - name:                       AutobuildAutobuild
        uses:                       ./android/autobuild
        
  release_mac:
    name:                           MacOSMacOS
    steps:
      - name:                       AutobuildAutobuild
        uses:                       ./mac/autobuild
