#### Automatically build and upload releases to GitHub ####

on:
  [workflow_dispatch, push]
name:                               MyTests1
jobs:        
  release_win:
    name:                           Autobuild Windows
    runs-on:                        windows-latest
    steps:
      - name:                       Checkout repository
        uses:                       actions/checkout@v2
      - name:                       AutobuildAutobuild
        uses:                       ./.github/actions_scripts/mytestaction1
        
        
  analyze:
    name: Analyze
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        #language: [ 'cpp', 'javascript', 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name:                       Checkout repository
        uses:                       actions/checkout@v2
      - name:                       Check ${{ matrix.os }}
        uses:                       ./.github/actions_scripts/mytestaction1
        
  release_mac:
    name:                           Autobuild MacOS
    needs:                          analyze
    runs-on:                        macos-latest
    steps:
      - name:                       Checkout repository
        uses:                       actions/checkout@v2
      - name:                       AutobuildAutobuild
        uses:                       ./.github/actions_scripts/mytestaction1